.PHONY: news_agent financial_agent host_agent

news_agent:
	python -m src.news_agent

financial_agent:
	python -m src.financial_agent

finance_agent:
	python -m src.financial_agent

host_agent:
	python -m src.host_agent

client: host_agent
